name: Golang script
author: Ofadiman
description: Run golang script.

branding:
  color: purple
  icon: globe

inputs:
  script:
    description: Golang script name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Debug
      shell: bash
      run: |
        echo "working directory at action path"
        ls -lrt ${{ github.action_path }} || true
        ls -lrt ${{ github.action_path }}/scripts/ || true
        echo ""

        echo "golang script at action path"
        cat ${{ github.action_path }}/${{ inputs.script }} || true
        echo ""

        echo "working directory at relative path"
        ls -lrt || true
        ls -lrt scripts/ || true
        echo ""

        echo "golang script at relative path"
        cat ${{ inputs.script }} || true
        echo ""

    - name: Run script
      shell: bash
      run: go run ${{ inputs.script }}
